version: '3.8'

services:
  postgis:
    build:
      context: ./ms-parking/map-data
      dockerfile: Dockerfile.postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - parking-network

  osm2pgsql:
    build:
      context: ./ms-parking/map-data
      dockerfile: Dockerfile.osm2pgsql
    depends_on:
      - postgis
    environment:
      - PGPASSWORD=osmpass
    networks:
      - parking-network

  ms-parking:
    container_name: ms-parking
    environment:
      - POSTGIS_HOST=postgis
    build:
      context: ./ms-parking
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgis
    networks:
      - parking-network

  ms-usuario:
    container_name: ms-usuario
    build:
      context: ./ms-usuario
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo-db
    ports:
      - "3001:3001"
    networks:
      - user-service-network
    restart: on-failure:3

  ms-mensagens:
    container_name: ms-mensagens
    build:
      context: ./ms-mensagens
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - mongo-db
      - mysql-db
    ports:
      - "3002:3002"
    networks:
      - user-service-network
    restart: on-failure:3

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - .mongo:/data/db
    networks:
      - user-service-network
    restart: on-failure:3

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user-service-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

volumes:
  mysql_data:
  pg_data:

networks:
  user-service-network:
    driver: bridge
  parking-network:
    driver: bridge
