version: '3'
services:
  python:
    build: 
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

